FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.16-openshift-4.8

ARG SDK_VERSION=v0.19.1
RUN wget -qO /usr/local/bin/operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/$SDK_VERSION/operator-sdk-$SDK_VERSION-x86_64-linux-gnu
RUN chmod +x /usr/local/bin/operator-sdk

CMD ["/bin/bash"]
