apiVersion: v1
kind: ServiceAccount
metadata:
  name: marketplace-operator
  namespace: openshift-marketplace
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-production-edge: "true"
