kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: marketplace-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-production-edge: "true"
subjects:
- kind: ServiceAccount
  name: marketplace-operator
  namespace: openshift-marketplace
roleRef:
  kind: ClusterRole
  name: marketplace-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: marketplace-operator
  namespace: openshift-marketplace
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-production-edge: "true"
subjects:
- kind: ServiceAccount
  name: marketplace-operator
  namespace: openshift-marketplace
roleRef:
  kind: Role
  name: marketplace-operator
  apiGroup: rbac.authorization.k8s.io
