kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-marketplace-operator
subjects:
- kind: ServiceAccount
  name: marketplace-operator
  namespace: openshift-marketplace
roleRef:
  kind: ClusterRole
  name: marketplace-operator
  apiGroup: rbac.authorization.k8s.io
