apiVersion: "marketplace.redhat.com/v1alpha1"
kind: "OperatorSource"
metadata:
  name: "certified-operators"
  namespace: "openshift-marketplace"
  labels:
    opsrc-provider: certified
spec:
  type: appregistry
  endpoint: "https://quay.io/cnr"
  registryNamespace: "certified-operators"
  displayName: "Certified Operators"
  publisher: "Red Hat"
