apiVersion: "operators.coreos.com/v1alpha1"
kind: "CatalogSource"
metadata:
  name: "redhat-operators"
  namespace: "openshift-marketplace"
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
spec:
  sourceType: grpc
  image: registry.redhat.io/redhat/redhat-operator-index:v4.13
  displayName: "Red Hat Operators"
  publisher: "Red Hat"
  priority: -100
  updateStrategy:
    registryPoll:
      interval: 10m
  grpcPodConfig:
    securityContextConfig: restricted
    nodeSelector:
        node-role.kubernetes.io/master: ""
        kubernetes.io/os: "linux"
    priorityClassName: "system-cluster-critical"
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: Exists
      effect: "NoSchedule"
    - key: "node.kubernetes.io/unreachable"
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 120
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 120
