apiVersion: "operators.coreos.com/v1alpha1"
kind: "CatalogSource"
metadata:
  name: "redhat-operators"
  namespace: "openshift-marketplace"
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    operatorframework.io/priorityclass: 'system-cluster-critical'
spec:
  sourceType: grpc
  image: registry.redhat.io/redhat/redhat-operator-index:v4.8
  displayName: "Red Hat Operators"
  publisher: "Red Hat"
  priority: -100
  updateStrategy:
    registryPoll:
      interval: 10m
