apiVersion: "operators.coreos.com/v1alpha1"
kind: "CatalogSource"
metadata:
  name: "community-operators"
  namespace: "openshift-marketplace"
spec:
  sourceType: grpc
  image: registry.redhat.io/redhat/community-operator-index:latest
  displayName: "Community Operators"
  publisher: "Red Hat"
  priority: -400
  updateStrategy:
    registryPoll:
      interval: 10m
