apiVersion: "operators.coreos.com/v1alpha1"
kind: "CatalogSource"
metadata:
  name: "community-operators"
  namespace: "openshift-marketplace"
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    openshift.io/required-scc: restricted-v2
spec:
  sourceType: grpc
  image: registry.redhat.io/redhat/community-operator-index:v4.19
  displayName: "Community Operators"
  publisher: "Red Hat"
  priority: -400
  updateStrategy:
    registryPoll:
      interval: 10m
  grpcPodConfig:
    securityContextConfig: restricted
    nodeSelector:
        node-role.kubernetes.io/master: ""
        kubernetes.io/os: "linux"
    priorityClassName: "system-cluster-critical"
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: Exists
      effect: "NoSchedule"
    - key: "node.kubernetes.io/unreachable"
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 120
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 120
    memoryTarget: 120Mi
    extractContent:
      cacheDir: /tmp/cache
      catalogDir: /configs
