apiVersion: "operators.coreos.com/v1alpha1"
kind: "CatalogSource"
metadata:
  name: "redhat-marketplace"
  namespace: "openshift-marketplace"
spec:
  sourceType: grpc
  image: registry.redhat.io/redhat/redhat-marketplace-index:v4.8
  displayName: "Red Hat Marketplace"
  publisher: "Red Hat"
  priority: -300
  updateStrategy:
    registryPoll:
      interval: 10m
