// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/datastore/unmarshaler.go

// Package datastore is a generated GoMock package.
package datastore

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockManifestYAMLParser is a mock of ManifestYAMLParser interface
type MockManifestYAMLParser struct {
	ctrl     *gomock.Controller
	recorder *MockManifestYAMLParserMockRecorder
}

// MockManifestYAMLParserMockRecorder is the mock recorder for MockManifestYAMLParser
type MockManifestYAMLParserMockRecorder struct {
	mock *MockManifestYAMLParser
}

// NewMockManifestYAMLParser creates a new mock instance
func NewMockManifestYAMLParser(ctrl *gomock.Controller) *MockManifestYAMLParser {
	mock := &MockManifestYAMLParser{ctrl: ctrl}
	mock.recorder = &MockManifestYAMLParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockManifestYAMLParser) EXPECT() *MockManifestYAMLParserMockRecorder {
	return m.recorder
}

// Unmarshal mocks base method
func (m *MockManifestYAMLParser) Unmarshal(rawYAML []byte) (*StructuredOperatorManifestData, error) {
	ret := m.ctrl.Call(m, "Unmarshal", rawYAML)
	ret0, _ := ret[0].(*StructuredOperatorManifestData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unmarshal indicates an expected call of Unmarshal
func (mr *MockManifestYAMLParserMockRecorder) Unmarshal(rawYAML interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockManifestYAMLParser)(nil).Unmarshal), rawYAML)
}

// Marshal mocks base method
func (m *MockManifestYAMLParser) Marshal(marshaled *StructuredOperatorManifestData) (*OperatorManifestData, error) {
	ret := m.ctrl.Call(m, "Marshal", marshaled)
	ret0, _ := ret[0].(*OperatorManifestData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marshal indicates an expected call of Marshal
func (mr *MockManifestYAMLParserMockRecorder) Marshal(marshaled interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockManifestYAMLParser)(nil).Marshal), marshaled)
}
