#!/bin/bash

echo -n "Relative path to your manifest file: "
read FILE
FILENAME=${FILE%.*}
echo -n "Namespace in quay.io: "
read NAMESPACE
echo -n "Repository name in quay.io: "
read REPOSITORY
echo -n "Version/Release of operator: "
read RELEASE
echo -n "Quay.io token (TOKEN value of ./scripts/get-quay-token ): "
read TOKEN

function cleanup() {
    rm -f ${FILENAME}.tar.gz
}
trap cleanup EXIT

tar czf ${FILENAME}.tar.gz ${FILENAME}.yaml

BLOB=$(cat ${FILENAME}.tar.gz | base64 -w 0)

curl -H "Content-Type: application/json" \
     -H "Authorization: ${TOKEN}" \
     -XPOST https://quay.io/cnr/api/v1/packages/${NAMESPACE}/${REPOSITORY} -d '
{
    "blob": "'"${BLOB}"'",
    "release": "'"${RELEASE}"'",
    "media_type": "helm"
}'